wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1729741334.765483
    t:
      1:
      - 1
      - 5
      - 30
      - 41
      - 49
      - 53
      - 54
      - 55
      - 63
      - 77
      2:
      - 1
      - 5
      - 30
      - 41
      - 49
      - 53
      - 54
      - 55
      - 63
      - 77
      3:
      - 13
      - 23
      4: 3.11.5
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
